# Generated by Django 2.0.10 on 2019-02-05 09:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pierwszy_Wpis',
            new_name='Post',
        ),
    ]
